[package]
name = "gyr"
version = "0.1.0"
authors = ["Namkhai B. <namkhai.n3@protonmail.com>"]
edition = "2018"

description = "A blazing fast TUI launcher for *BSD and Linux"

repository = "https://gitlab.com/forkbomb9/gyr"
readme = "README.md"
keywords = []
license = "BSD-2-Clause"

[badges]
# GitLab CI
gitlab = { repository = "forkbomb9/gyr"}

[profile.release]
lto = true

[dependencies]
eyre = "0.6"
lexopt = "0.2"
directories = "4.0"
dirs = "4.0"
fuzzy-matcher = "0.3"
libc = "0.2"
safe-regex = "0.2"
serde = { version = "1", features = ["derive"] }
shell-words = "1.0"
sled = "0.34"
termion = "1.5"
toml = "0.5"
tui = { version = "0.17", default-features = false, features = ["termion"] }
