[package]
name = "flauncher"
version = "0.1.0"
authors = ["Namkhai B. <namkhai.n3@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
anyhow = "1.0"
fuzzy-filter = "0.1"
libc = "0.2"
regex = "1"
serde = { version = "1", features = ["derive"] }
termion = "1.5"
toml = "0.5"
tui = "0.8"
