[package]
name = "gyr"
version = "0.1.0"
authors = ["Namkhai B. <namkhai.n3@protonmail.com>"]
edition = "2018"

description = "A blazing fast TUI launcher for *BSD and Linux"

repository = "https://gitlab.com/forkbomb9/gyr"
readme = "README.md"
keywords = []
license = "BSD-2-Clause"

[badges]
# GitLab CI
gitlab = { repository = "forkbomb9/gyr"}

[dependencies]
anyhow = "1.0"
clap = "2.33"
directories = "3.0"
fuzzy-matcher = "0.3"
libc = "0.2"
regex = "1"
serde = { version = "1", features = ["derive"] }
termion = "1.5"
toml = "0.5"
tui = "0.13"
